### ISSUE TITLE
I am getting an error “429” on my Homey Pro 2023 from my Wallbox Pulsar Plus software v6.7.26

### ISSUE THREAD

**Issue by edbjan** [rkokkelk/nl.xseth.wallbox#47]
Hi
I am getting an error “429” on my Homey Pro 2023 from my Wallbox Pulsar Plus software v6.7.26
It starts today. June 17, 2025

plx look in attache-doc

[20250617-Wallbox-Homey-Fejl-429-02.docx](https://github.com/user-attachments/files/20780499/20250617-Wallbox-Homey-Fejl-429-02.docx)

Thanks in advance
Jan Olsen

**Comment by linden85** [comment]
Hallo,

I have also error code 429



640b88f2-778d-4dd4-a61c-1ef1c2b0cdd4

![image](https://github.com/user-attachments/assets/04f5c639-151f-479e-b7f4-3f58df5e035b)

**Comment by MMP1978** [comment]
FYI

Same issue on Home Assistant integration. 
Seems like an API change from Wallbox. :(

https://github.com/home-assistant/core/issues/147022

**Comment by heszegi** [comment]
Same error here, it looks like the Wallbox API has undergone some changes, and a 15-second polling interval is now too frequent. Every second call made within 60 seconds returns an HTTP 429 (Too Many Requests).

**Comment by NikJoos** [comment]
Happy to see I’m not the only one with this issue.
Anyone that can update the polling interval to 61seconds?  Or can we update setting to reduce the interval locally?

**Comment by hesselonline** [comment]
Hi, I'm the developer for the Home Assistant integration. Just a quick thought, it might be useful if we start making support tickets for this. I honestly think we will need action on the side of wallbox to really resolve this. Mention the http error and the wallbox integration. I have already done this from my side.

**Comment by StijnDamen** [comment]
This is exactly the error I'm also getting with my homey since the update.

**Comment by verdierpe** [comment]
Same Issue here. Deleted the device to try a new login, but even here I received an Error 429.  Just installer my Wall Box recently so I had no flows running yet.

**Comment by FredV1904** [comment]
Yep, started here as well since yesterday. The app on IOS seems to have been changed as well. Extreemly annoying as their own green charging doesn't work and my flow can't execute 4 out of 5 times.

**Comment by FredV1904** [comment]
@hesselonline 

Tell me where and I'll do it.

**Comment by hesselonline** [comment]
This is what other users are doing:

Subject:
Urgent: Persistent HTTP 429 Errors in Home Assistant Integration (Charger ID: xxxxx)

Message:
Dear Wallbox Support,

I’m experiencing critical API issues with the official Home Assistant Wallbox integration. Since [date/time], my system has been consistently receiving HTTP 429 ("Too Many Requests") errors when attempting to fetch charger status data, despite no configuration changes on my end.

Key Details:
Charger ID: xxxxxx

Error:

python
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for URL: https://api.wall-box.com/chargers/status/xxxxxx
First Occurrence: xx:xx (41 repeated errors as of xx:xx)

Troubleshooting Steps Taken:

Confirmed the Wallbox mobile app works normally (suggests an API-specific issue).

Questions:
Are there ongoing API rate limit changes or service disruptions?

Could my charger (ID: xxxxxx) have been throttled by your systems?

What is the recommended request rate for third-party integrations like Home Assistant?

E-mail: support@wallbox.com

Website: https://support.wallbox.com/

**Comment by eelko123** [comment]
Same issue here.

Have many flows also mimics of the solar charging if anyone is interested.

Though first this issue needs resolvement.
I have contacted wallbox but no news yet.

Kudos to @rkokkelk the app is amazing!
Really thank you for the development!!

Hope you can also put your magic in solving this issue.

**Comment by FredV1904** [comment]
Is it me or do others see this as well:
Starting/pausing charging sometimes works

Changinging the power never works.

**Comment by eelko123** [comment]
@FredV1904 I could always change power vis homey (that was before the 429 issue occured).

What I did in my flow was
1) put charging on pause
2) change ampere with delay of 4 sec
3) continue charging with delay of 4 sec

Worked like a charm
Though now having the 429 issue

**Comment by Barney1977** [comment]
H I have the same issue

**Comment by NikJoos** [comment]
Wallbox support request sent

**Comment by Cuprani** [comment]
Same issue here.
Occasionally I can reach 1 of my 2 wallboxes. The second one is never reachable anymore.

With dynamic energy tariffs it cost me hundreds of Euro's a year not being able to control my charges anymore.
This is unacceptable from Wallbox side, they sold the Wallbox as fully controllable over API.

![Image](https://github.com/user-attachments/assets/8bc242d3-6b0f-4c1a-9161-ae947ff7ba59)

Please send a complain [to them](https://support.wallbox.com/en/contact-us/). 
Maybe if they receive enough claims they will recover the API functionality as it was.

**Comment by verdierpe** [comment]
Done! I have written a complain to Wallbox.

**Comment by FredV1904** [comment]
I just received this response. Anyone else had it?

Thank you for contacting Wallbox Support
Can you let us know what exactly is happening with your charger?
And please send an screenshot of the error message that appears, Many thanks!

Also, please do not hesitate to follow these first troubleshooting steps to solve any charging issue:

Perform a long power cycle: switch off the Wallbox at the fuse box for 2 minutes, then turn it back on and wait for the green light to appear.
Connect your charger to Bluetooth and Wi-Fi.
Restart via the app.
Restore the charger via the app and try to connect.
Attempt a new charge and observe the charger’s behavior.
Update your charger.
Attempt a new charge and observe the charger’s behavior.
If the problem persists, please send us a video showing you connecting the cable to the vehicle and then the behavior of the charger.

Thank you in advance, and I look forward to your response.
Have a lovely day
Best Regards



Erik Janson
Wallbox service support Team

**Comment by Barney1977** [comment]
Already tried that yesterday. Still having the same troubles.
________________________________
Van: FredV1904 ***@***.***>
Verzonden: donderdag 19 juni 2025 14:41
Aan: rkokkelk/nl.xseth.wallbox ***@***.***>
CC: Barney1977 ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [rkokkelk/nl.xseth.wallbox] I am getting an error “429” on my Homey Pro 2023 from my Wallbox Pulsar Plus software v6.7.26 (Issue #47)

[https://avatars.githubusercontent.com/u/166021826?s=20&v=4]FredV1904 left a comment (rkokkelk/nl.xseth.wallbox#47)<https://github.com/rkokkelk/nl.xseth.wallbox/issues/47#issuecomment-2987970925>

I just received this response. Anyone else had it?

Thank you for contacting Wallbox Support
Can you let us know what exactly is happening with your charger?
And please send an screenshot of the error message that appears, Many thanks!

Also, please do not hesitate to follow these first troubleshooting steps to solve any charging issue:

Perform a long power cycle: switch off the Wallbox at the fuse box for 2 minutes, then turn it back on and wait for the green light to appear.
Connect your charger to Bluetooth and Wi-Fi.
Restart via the app.
Restore the charger via the app and try to connect.
Attempt a new charge and observe the charger’s behavior.
Update your charger.
Attempt a new charge and observe the charger’s behavior.
If the problem persists, please send us a video showing you connecting the cable to the vehicle and then the behavior of the charger.

Thank you in advance, and I look forward to your response.
Have a lovely day
Best Regards

Erik Janson
Wallbox service support Team

**Comment by eelko123** [comment]
Same

Wallbox asked me to perform a disconnect for >2hours, i did all that. No difference.
Also deleted the wallbox from homey and re-installed, no difference (i also do not recommend this to anyone, as it means you can rewrite your flows again)... 

Wallbox seem not really to understand "API" and "Homey", tried to explain it quite a few times. Unfortunately not resolved from my end yet. I hope it will be soon.

If anyone has a solution, i hope it will be shared here.

**Comment by FredV1904** [comment]
follow here, It's on home assistant but if that gets solved so does the Homey one probably.

https://github.com/home-assistant/core/issues/147022

**Comment by FredV1904** [comment]
It seems to be working again for many Home Assistent users. Not so for me on Homey. Does it work for anyone?

**Comment by NikJoos** [comment]
Some info gets thru. But after triggering a state change it’s 429 again…

**Comment by heszegi** [comment]
Hi @rkokkelk,

I found a possible solution, adding the "User-Agent" header to the request may help resolve the communication issue. I’m currently testing it locally, and the app has been working as expected for a while now.

I’ve created a PR for your code (https://github.com/rkokkelk/nl.xseth.wallbox/pull/49). Please review it, and if it looks good, kindly merge it and publish a test app for broader testing.

**Comment by eelko123** [comment]
@rkokkelk  / others,

Below i received from Wallbox. I have translated it into english, original text was in dutch:

API Service Update – June 2025

Subject: Improvements in API performance and new usage policy

We have recently identified unusually high and inefficient traffic to our API, particularly from certain third-party services such as Home Assistant / Homey. This has occasionally impacted performance and reliability for other users. To address this, we are rolling out the following updates:

What’s new

Upgraded API infrastructure to better handle concurrent requests and ensure long-term scalability.

New usage policy aimed at encouraging rational and sustainable integration patterns on external platforms.

Improved rate-limiting logic – the current system will be adjusted to provide more balanced access without compromising overall stability.

Why this matters

Some integrations, due to inefficient polling or redundant requests, have placed an excessive load on our servers. Our new system will help minimize these issues while continuing to support open and flexible integration.

What you should do

If you maintain an integration with our API (e.g., via Home Assistant / Homey), we strongly recommend reviewing your implementation to ensure it aligns with the new guidelines. Avoid unnecessary or frequent polling. Where possible, consider using caching, event-based logic, or batching.

When

These changes will be rolled out gradually starting June 18, 2025.

For developers: Detailed technical documentation and updated rate limits will soon be available in the Developer Portal.

Thank you for your cooperation and commitment to responsible usage.

— The API Team

**Comment by FredV1904** [comment]
@eelko123 

Good to know, understandable even but it would have been nice if they would have informed everyone earlier and if they would have released documentation before making the change.
So, that means changing the code which will take a bit of time I guess.

Has anyone heard from the devlopper/owner @rkokkelk yet? 

Meanwhile I'm using the Wallbox app on solar change mode but that is a very primitive way of working. It doesn't even change the powerlimit in function of the amount of solar remaining.

**Comment by Davezelf** [comment]
> I just received this response. Anyone else had it?
> 
> Thank you for contacting Wallbox Support Can you let us know what exactly is happening with your charger? And please send an screenshot of the error message that appears, Many thanks!
> 
> Also, please do not hesitate to follow these first troubleshooting steps to solve any charging issue:
> 
> Perform a long power cycle: switch off the Wallbox at the fuse box for 2 minutes, then turn it back on and wait for the green light to appear. Connect your charger to Bluetooth and Wi-Fi. Restart via the app. Restore the charger via the app and try to connect. Attempt a new charge and observe the charger’s behavior. Update your charger. Attempt a new charge and observe the charger’s behavior. If the problem persists, please send us a video showing you connecting the cable to the vehicle and then the behavior of the charger.
> 
> Thank you in advance, and I look forward to your response. Have a lovely day Best Regards
> 
> Erik Janson Wallbox service support Team

**Comment by Davezelf** [comment]
Here the exact same answer.

**Comment by eelko123** [comment]
> [@eelko123](https://github.com/eelko123)
> 
> Good to know, understandable even but it would have been nice if they would have informed everyone earlier and if they would have released documentation before making the change. So, that means changing the code which will take a bit of time I guess.
> 
> Has anyone heard from the developer/owner [@rkokkelk](https://github.com/rkokkelk) yet?
> 
> Meanwhile I'm using the Wallbox app on solar change mode but that is a very primitive way of working. It doesn't even change the powerlimit in function of the amount of solar remaining.


@FredV1904 no unfortunately no reply from @rkokkelk. I can fully understand all you guys have other things on your mind and this is a "hobby". But for digital gremlins you make our life amazing and these apps are really great. It not functioning is as having this weekend no sunshine... 

I hope you guys can help out soon. Using the wallbox app solely doesnt quite do it, integration with time, electricity pricing, sun, etc is really teriffic. I am using it via homey others via home assist, either or it just make life easier.

hopefully we can get it resolved. Kuddos to all doing efforts. Really appreciate it.

**Comment by rkokkelk** [comment]
Hey Guys,

Unfortunately due to work and family obligations I haven't got around to fixing it yet. But I'll make time this weekend to resolve it as fast as possible. Unfortunately this has been a surprise for me as for you guys. I'll also contact the Wallbox to get more insight into the current requirements surrounding there API ensure that the Homey integrations follows it. 

If there are any updates, relevant commits, test versions I'll let you guys know in this issue.

**Comment by rkokkelk** [comment]
Okay I've released a branch with some potential fixes: https://github.com/rkokkelk/nl.xseth.wallbox/tree/fix/47. However, due to some issues that I'm having with my dev environment I currently can't  run or build it. I'll try to fix that as soon as possible but hopefully someone else can quickly verify whether this resolves the issues, so far.

**Comment by siepiee** [comment]
Can you also add the capability straight away Wallbox is visible the energy tab. If I am right athom have send you a mail.

**Comment by siepiee** [comment]
Can you also add the capability straight away Wallbox is visible the energy tab. If I am right athom have send you a mail.

**Comment by rkokkelk** [comment]
> Can you also add the capability straight away Wallbox is visible the energy tab. If I am right athom have send you a mail.

Please create a separate issue for this, because this is a new FR.

**Comment by Jan-Wijnja** [comment]
If you remove the device from Homey and try to add it again (and thus log in to Wallbox) you immediately get 429, which seems to be a connectivity or authentication issue

**Comment by siepiee** [comment]
> > Can you also add the capability straight away Wallbox is visible the energy tab. If I am right athom have send you a mail.
> 
> Please create a separate issue for this, because this is a new FR. 

I did a while ago

**Comment by hesselonline** [comment]
@rkokkelk I had a meeting with the wallbox software team today to discuss the rate limiting issues. I mentioned that you also had a Homey integration which had similar problem. They were open to a meeting to discuss this. Let me know if I should link you to them.

**Comment by Davezelf** [comment]
At this point, I’ve listed my Wallbox for sale on Marktplaats as a precaution.

The API functionality was a key reason I chose Wallbox in the first place. With the recent unilateral change on their side, the charger has become unusable for my Homey setup. I personally call this: a unilateral change of the delivery conditions.

If Wallbox is unwilling to offer a solution, I’m seriously considering further steps regarding compensation. And frankly, if this is their direction going forward, I don’t ever want to deal with the company Wallbox again.

Fortunately, there are plenty of alternatives that do integrate well with smart home platforms like Homey. I’m considering brands such as Easee, Zaptec, Alfen, Go-e, or even EVCC combined with an open charge point via OCPP. The latter may require more technical effort but at least it gives control back to the user.

I’m curious how others are dealing with this. Has anyone had contact with Wallbox yet, or already switched to a better alternative?

**Comment by hesselonline** [comment]
@Davezelf please read my last post directly above yours. I had a meeting today with Wallbox, representing the Home Assistant integration. I found their approach very reasonable, and they were open to finding a solution.

**Comment by Davezelf** [comment]
@hesselonline  Good to hear that, Hessel. But completely shutting everything down is a different story in my opinion.
Why not allow just one API call every 10 minutes or so? That would already be enough for most of us who know how to write a basic flow or integration. No one needs real-time second-by-second updates — just some level of access to make intelligent automation possible.

**Comment by hesselonline** [comment]
@Davezelf actually they are allowing multiple requests per minute at the moment. Before (last week), the cap was set at 1 request every minute.

**Comment by Davezelf** [comment]
@hesselonline Okay, that’s already something — I understand you’re from the Home Assistant crowd, where things are still working.
But here on Homey, it’s currently broken.

So we Homey users will just have to wait until Roy has had the chance to rewrite things? (No criticism towards Roy at all — I’m sure he has his reasons, and I appreciate the work he’s done so far.)

**Comment by hesselonline** [comment]
@Davezelf we welcome new users at Home Assistant;-). 
Basically I understand that Wallbox needs to ensure that there servers are able to handle the load for the api requests made. I thought they were really respectful in the resulting conversation. 
Not sure how that translates to Homey users, apart from the fact that they seemed willing to have a conversation with your developers.

**Comment by Davezelf** [comment]
@hesselonline You made things clearer than my energy meter at 3 a.m. cheers!

**Comment by rkokkelk** [comment]
> [@rkokkelk](https://github.com/rkokkelk) I had a meeting with the wallbox software team today to discuss the rate limiting issues. I mentioned that you also had a Homey integration which had similar problem. They were open to a meeting to discuss this. Let me know if I should link you to them.

@hesselonline great to hear that you have a successful conversation with them. Please feel free to forward my temporary contact details (rkokk-wallbox@proton.me). 

Unfortunately so far I haven't got my dev environment fixed so I can test the current dev brand. I hope that this Friday I can find some time to get everything up and running.

**Comment by BerndGaykema** [comment]
@Davezelf , consider [this ](https://homey.app/en-nl/app/com.aminacharging/amina/)one.

Can't wait for Friday ..... ;-)

**Comment by rkokkelk** [comment]
I've just published a test version which should resolve the issues. I would request that as many people as possible try this test version in order to validate whether it actually resolves the API 429 issues. 

* https://homey.app/a/nl.xseth.wallbox/test/

**Comment by siepiee** [comment]
For me it seems to be fixed. Amazing. Thanks for the great work. Can you also look at the other issue I opened. I think it's a small thing. Athom send you a mail to add the correct capability.

**Comment by FredV1904** [comment]
Installed and after 20minutes it hasn’t reported an error and looks like it is charging the car.

Excellent job. Let’s hope it keeps going

**Comment by eelko123** [comment]
Wholy f***

Installed. Worked instantly.
@rkokkelk AMAZING!!!!

**Comment by linden85** [comment]
@rkokkelk i am afraid no solution first i updated the app no solution and after i removed the Wallbox and after reinstalling error code 403

**![image](https://github.com/user-attachments/assets/a6dda8dd-da1b-4d5f-a231-bcd58ea4ca13)**

**Comment by rkokkelk** [comment]
> [@rkokkelk](https://github.com/rkokkelk) i am afraid no solution first i updated the app no solution and after i removed the Wallbox and after reinstalling error code 403
> 
> **![image](https://github.com/user-attachments/assets/a6dda8dd-da1b-4d5f-a231-bcd58ea4ca13)**

This error code is different than this initial issue, with regards to the HTTP responses 429. Getting a 403 means that the API has parsed the response so maybe it is a different issue.

However, I've also tried the same sequence of removing my device and adding it as a new install and that has succeeded. So maybe something wrong with your authorization within your app or maybe invalid credentials. Either way I think it is something different than this issue.

**Comment by rkokkelk** [comment]
I've published the test version to production which should be updated on all devices. If there are still any API issues, please feel free to open a new issue.

**Comment by linden85** [comment]
@rkokkelk thanks for you're help.
After a successful login /reinstall of my Wallbox I can't see my Wallbox in my dashboard and I didn't see the recognition of ev lader in Homey.


![image](https://github.com/user-attachments/assets/b4f650d0-96d3-4225-9a3c-9f6af0eeec28)

![image](https://github.com/user-attachments/assets/65d3bceb-f440-410e-a3d2-1d309ab84be8)

**Comment by rkokkelk** [comment]
> [@rkokkelk](https://github.com/rkokkelk) thanks for you're help. After a successful login /reinstall of my Wallbox I can't see my Wallbox in my dashboard and I didn't see the recognition of ev lader in Homey.
> 
> ![image](https://github.com/user-attachments/assets/b4f650d0-96d3-4225-9a3c-9f6af0eeec28)
> 
> ![image](https://github.com/user-attachments/assets/65d3bceb-f440-410e-a3d2-1d309ab84be8)

Yeah that is a separate issue, apparently I need to make some changes in the app before it is in shown in the Energy dashboard. See #46, for the progress.

**Comment by Davezelf** [comment]
@rkokkelk Dear Roy,

Thank you once again for the time and effort you've put into this. I installed the update yesterday via the phone and initially got a 403 error. But when I came home today, everything was working perfectly.

You've made someone very happy again. Hats off to you!

Best regards,
Dave

**Comment by edbjan** [comment]
Hi
It's a great job you've done here, Homey and Wallbox work together perfectly again
Thank you very much and this case can be closed ;)

**Comment by robmalschaert** [comment]
Great job! I’ve reinstalled the app and have now succesfully connected the device again. 

Have you got a buymeacoffee or something like that?
